/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import obchod.Kosik;
import obchod.Obchod;
import obchod.Zbozi;

/**
 *
 * @author bauerpe1
 */
public class FObchod extends javax.swing.JFrame
{
    private final Obchod obchod;
    private final Kosik kosik;
   
    public FObchod() {
        obchod = new Obchod();
        kosik = new Kosik();
        initComponents();
        lstNabidka.setListData(obchod.nabidkaAsStringArray());
        lstNakup. setListData(kosik.asStringArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEditor = new javax.swing.JPanel();
        labNazev = new javax.swing.JLabel();
        labMnozstvi = new javax.swing.JLabel();
        tfNazev = new javax.swing.JTextField();
        tfMnozstvi = new javax.swing.JTextField();
        btPridatZbozi = new javax.swing.JButton();
        labCena = new javax.swing.JLabel();
        tfCena = new javax.swing.JTextField();
        labJednotka = new javax.swing.JLabel();
        cbJednotka = new javax.swing.JComboBox<>();
        labEdit = new javax.swing.JLabel();
        scPaneVystup = new javax.swing.JScrollPane();
        vystup = new javax.swing.JTextArea();
        jLabObchod = new javax.swing.JLabel();
        pNabidka = new javax.swing.JPanel();
        scPaneNabidka = new javax.swing.JScrollPane();
        lstNabidka = new javax.swing.JList<>();
        labNabidka = new javax.swing.JLabel();
        btNacistNabidku = new javax.swing.JButton();
        btUlozitNabidku = new javax.swing.JButton();
        btOdstranitZbozi = new javax.swing.JButton();
        btVymazatNabidku = new javax.swing.JButton();
        pKosik = new javax.swing.JPanel();
        labKosik = new javax.swing.JLabel();
        scPaneKosik = new javax.swing.JScrollPane();
        lstNakup = new javax.swing.JList<>();
        btKoupit = new javax.swing.JButton();
        btPlus = new javax.swing.JButton();
        btMinus = new javax.swing.JButton();
        btVyprazdnitKosik = new javax.swing.JButton();
        btTisknoutUctenku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labNazev.setText("název");

        labMnozstvi.setText("jednotkové množství");

        btPridatZbozi.setText("Přidat zboží do nabídky");

        labCena.setText("jednotková cena");

        labJednotka.setText("jednotka");

        cbJednotka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "ks", "kg", "l" }));

        labEdit.setText("Editor zboží");

        javax.swing.GroupLayout pEditorLayout = new javax.swing.GroupLayout(pEditor);
        pEditor.setLayout(pEditorLayout);
        pEditorLayout.setHorizontalGroup(
            pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labEdit)
                    .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labNazev)
                        .addComponent(labMnozstvi)
                        .addComponent(labCena)
                        .addComponent(labJednotka)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJednotka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNazev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addComponent(tfMnozstvi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfCena, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(145, 145, 145))
            .addGroup(pEditorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btPridatZbozi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEditorLayout.setVerticalGroup(
            pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditorLayout.createSequentialGroup()
                .addComponent(labEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNazev)
                    .addComponent(tfNazev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMnozstvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labMnozstvi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCena)
                    .addComponent(tfCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labJednotka)
                    .addComponent(cbJednotka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btPridatZbozi)
                .addContainerGap())
        );

        vystup.setColumns(20);
        vystup.setRows(5);
        scPaneVystup.setViewportView(vystup);

        jLabObchod.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabObchod.setText("Offline obchod KupsiCoChceš");

        scPaneNabidka.setViewportView(lstNabidka);

        labNabidka.setText("Nabídka obchodu");

        btNacistNabidku.setText("Načíst nabídku");
        btNacistNabidku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNacistNabidkuActionPerformed(evt);
            }
        });

        btUlozitNabidku.setText("Uložit nabídku");
        btUlozitNabidku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUlozitNabidkuActionPerformed(evt);
            }
        });

        btOdstranitZbozi.setText("Odstranit položku");

        btVymazatNabidku.setText("Vymazat nabídku");

        javax.swing.GroupLayout pNabidkaLayout = new javax.swing.GroupLayout(pNabidka);
        pNabidka.setLayout(pNabidkaLayout);
        pNabidkaLayout.setHorizontalGroup(
            pNabidkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNabidkaLayout.createSequentialGroup()
                .addGroup(pNabidkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNabidkaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scPaneNabidka, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pNabidkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btNacistNabidku)
                            .addComponent(btVymazatNabidku)
                            .addComponent(btUlozitNabidku)
                            .addComponent(btOdstranitZbozi)))
                    .addGroup(pNabidkaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labNabidka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNabidkaLayout.setVerticalGroup(
            pNabidkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNabidkaLayout.createSequentialGroup()
                .addComponent(labNabidka, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNabidkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNabidkaLayout.createSequentialGroup()
                        .addComponent(btNacistNabidku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUlozitNabidku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVymazatNabidku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btOdstranitZbozi))
                    .addComponent(scPaneNabidka, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        labKosik.setText("Nákupní košík");

        scPaneKosik.setViewportView(lstNakup);

        btKoupit.setText("Koupit");

        btPlus.setText("+");

        btMinus.setText("-");

        btVyprazdnitKosik.setText("Vyprázdnit košík");

        btTisknoutUctenku.setText("Tisknout Účtenku");

        javax.swing.GroupLayout pKosikLayout = new javax.swing.GroupLayout(pKosik);
        pKosik.setLayout(pKosikLayout);
        pKosikLayout.setHorizontalGroup(
            pKosikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKosikLayout.createSequentialGroup()
                .addGroup(pKosikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKosikLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pKosikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pKosikLayout.createSequentialGroup()
                                .addComponent(scPaneKosik, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pKosikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btPlus)
                                    .addComponent(btMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btKoupit)))
                            .addGroup(pKosikLayout.createSequentialGroup()
                                .addComponent(btVyprazdnitKosik)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btTisknoutUctenku))))
                    .addGroup(pKosikLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(labKosik)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pKosikLayout.setVerticalGroup(
            pKosikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKosikLayout.createSequentialGroup()
                .addComponent(labKosik, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pKosikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKosikLayout.createSequentialGroup()
                        .addComponent(btKoupit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMinus))
                    .addComponent(scPaneKosik, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pKosikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVyprazdnitKosik)
                    .addComponent(btTisknoutUctenku))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabObchod))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNabidka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pKosik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scPaneVystup, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabObchod)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pNabidka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pKosik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(scPaneVystup, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUlozitNabidkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUlozitNabidkuActionPerformed
        JFileChooser fch = new JFileChooser();
        fch.setCurrentDirectory(new File (System.getProperty("user.dir")));
        if (fch.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File f = fch.getSelectedFile();
            boolean commence = true;
            
            if (f.exists())
            {
                //JDialog.setDefaultLookAndFeelDecorated(true);
                int response = JOptionPane.showConfirmDialog(this, "Zadaný soubor již existuje, přepsat?", "Uložit seznam zboží", JOptionPane.YES_NO_CANCEL_OPTION);
                if (response != JOptionPane.YES_OPTION)
                    commence = false;
            }
            if (commence)
                obchod.ulozNabidku(f);
        }
        vystup.setText("");
    }//GEN-LAST:event_btUlozitNabidkuActionPerformed

    private void btNacistNabidkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNacistNabidkuActionPerformed
        JFileChooser fch = new JFileChooser();
        fch.setCurrentDirectory(new File (System.getProperty("user.dir")));
        if (fch.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            boolean commence = true;
            
            if (lstNabidka.getModel().getSize() > 0)
            {
                int response = JOptionPane.showConfirmDialog(this, "Aktuální seznam zboží není prázdný, pokračovat s načítáním?", "Načíst seznam zboží", JOptionPane.YES_NO_CANCEL_OPTION);
                if (response != JOptionPane.YES_OPTION)
                    commence = false;
            }
            if (commence)
                obchod.nactiNabidku(fch.getSelectedFile());
        }
        lstNabidka.setListData(obchod.nabidkaAsStringArray());
        vystup.setText("");
    }//GEN-LAST:event_btNacistNabidkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args)
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FObchod().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKoupit;
    private javax.swing.JButton btMinus;
    private javax.swing.JButton btNacistNabidku;
    private javax.swing.JButton btOdstranitZbozi;
    private javax.swing.JButton btPlus;
    private javax.swing.JButton btPridatZbozi;
    private javax.swing.JButton btTisknoutUctenku;
    private javax.swing.JButton btUlozitNabidku;
    private javax.swing.JButton btVymazatNabidku;
    private javax.swing.JButton btVyprazdnitKosik;
    private javax.swing.JComboBox<String> cbJednotka;
    private javax.swing.JLabel jLabObchod;
    private javax.swing.JLabel labCena;
    private javax.swing.JLabel labEdit;
    private javax.swing.JLabel labJednotka;
    private javax.swing.JLabel labKosik;
    private javax.swing.JLabel labMnozstvi;
    private javax.swing.JLabel labNabidka;
    private javax.swing.JLabel labNazev;
    private javax.swing.JList<String> lstNabidka;
    private javax.swing.JList<String> lstNakup;
    private javax.swing.JPanel pEditor;
    private javax.swing.JPanel pKosik;
    private javax.swing.JPanel pNabidka;
    private javax.swing.JScrollPane scPaneKosik;
    private javax.swing.JScrollPane scPaneNabidka;
    private javax.swing.JScrollPane scPaneVystup;
    private javax.swing.JTextField tfCena;
    private javax.swing.JTextField tfMnozstvi;
    private javax.swing.JTextField tfNazev;
    private javax.swing.JTextArea vystup;
    // End of variables declaration//GEN-END:variables
}
